config/routes.rb
MagicEstimation::Application.routes.draw do

  

  root to: 'backlogs#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :backlogs do
    resources :items, only: [:create, :edit, :update, :destroy] do
      member do
        post :assign, to: :assign
      end
      resources :estimations, only: [:index]
    end
    member do
      get '/estimations/initial', to: 'estimations#initial'
      get '/estimations/next', to: 'estimations#next'
      get '/estimations/reestimate', to: 'estimations#reestimate'
      post '/estimations/pass', to: 'estimations#pass'
    end
  end
  resources :estimations, only: [:index]
end

app/models/estimation.rb
class Estimation < ActiveRecord::Base

  validates :user_id, presence: true
  validates :initial, inclusion: { in: [true,false] }

  belongs_to :item
  belongs_to :estimator, foreign_key: 'user_id', class_name: 'User'

  default_scope order(:updated_at)
  scope :total, ->(estimator) {where(user_id: estimator.id)}
  scope :initial, ->(estimator) { total(estimator).where(initial: true)}
  scope :initial_not_estimated_yet, ->(estimator) { initial(estimator).where(value: nil)}
  scope :initial_already_estimated, ->(estimator) { initial(estimator).where.not(value: nil)}
end

app/controllers/estimations_controller.rb
class EstimationsController < ApplicationController

  before_action :require_user

  def index
    if params[:backlog_id] && params[:item_id]
      @estimations = Estimation.joins(:item).joins(:estimator).where(:'items.backlog_id'=> params[:backlog_id], :'estimations.item_id' => params[:item_id]).select('estimations.value', 'users.name', 'users.id user_id')
      respond_to do |format|
        format.html { render partial: 'estimations/value_per_user'}
        format.json { render json: @estimations}
      end
    end
  end

  def initial
    backlog = Backlog.find(params[:id])
    items = Item.for_backlog_and_estimator_to_be_estimated_initially(backlog,current_user)
    if !items.empty?
      @item = items.first
      @estimated = Item.for_backlog_and_estimator_already_estimated(backlog,current_user).size
      @total = items.size + @estimated
    else
      flash[:error] = 'There are no items to be estimated initially.'
      redirect_to estimations_path
    end
  end

  def next
    backlog = Backlog.find(params[:id])
    items = Item.for_backlog_and_estimator_to_be_estimated_next(backlog, current_user)
    if !items.empty?
      @item = items.first
      @estimated = Item.for_backlog_and_estimator_already_estimated(backlog, current_user).size
      @total = items.size + @estimated
    else
      flash[:notice] = 'There are no items to be estimated as next.'
      redirect_to estimations_path
    end
  end

  def reestimate
    backlog = Backlog.find(params[:id])
    items = Item.for_backlog_to_be_reestimated(backlog)
    if !items.empty?
      @total = items.size
      @estimated = get_pos-1
      if @estimated >= @total
        flash[:notice] = 'You are done with the reestimation.'
        redirect_to root_path
      else
        @item = items[@estimated]
      end
    else
      flash[:notice] = 'There are no items to be re-estimated'
      redirect_to estimations_path
    end
  end

  def pass
    item = Item.find(params[:item_id])
    estimation = item.estimate(current_user, params[:value])
    if estimation
      flash.now[:notice] = "Your estimation of #{estimation.value} story points for item #{item.name} has been submitted."
    else
      flash.now[:error] = 'Something went wrong.'
    end
    if estimation.initial?
      redirect_to estimations_initial_backlog_path(item.backlog)
    else
      if params[:pos]
        pos = get_pos
        redirect_to estimations_reestimate_backlog_path(item.backlog,pos: pos+1)
      else
        redirect_to estimations_next_backlog_path(item.backlog)
      end
    end
  end

  private

  def get_pos
    pos = params[:pos].to_i || 1
    if pos == 0
      pos = 1
    end
    pos
  end
end

app/views/estimations/_dashboard.html.erb
<% i = 0 %>
<div class="container-fluid">
  <% Backlog.all.each do |backlog| %>
      <%= render inline: '<div class="row">' if i%2 == 0 %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= backlog.name %>
          </div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt>Total items:</dt>
              <dd><span class="label label-default"><%= backlog.items.count %></span></dd>
              <dt>Items to be assigned:</dt>
              <dd><span class="label label-danger"><%= Item.for_backlog_not_assigned(backlog).size %></span></dd>
              <dt>Items to be estimated:</dt>
              <dd><span class="label label-primary"><%= Item.for_backlog_not_estimated_yet(backlog).size %></span></dd>
              <dt>Items with at least 2 estimations:</dt>
              <dd><span class="label label-success"><%= Item.for_backlog_to_be_reestimated(backlog).size %></span></dd>
              <dt>Items with less than 2 estimations:</dt>
              <dd>
                <span class="label label-primary"><%= Item.for_backlog_not_sufficient_estimated(backlog).size %></span>
              </dd>
              <dt>&nbsp;</dt>
              <dd></dd>
              <dt>Top 3 with the highest deviation:</dt>
              <dd></dd>
            </dl>
            <table class="table table-bordered">
                <% j = 0 %>
                <% Item.standard_deviations(backlog).each do |item,deviation| %>
                    <% break if j == 3 %>
                    <tr><td><%=item.name%></td><td class="text-right-aligned"><%=deviation%></td></tr>
                    <% j+= 1 %>
                <% end %>
            </table>
          </div>
          <div class="panel-body">
            <table class="table table-striped table-hover">
              <thead>
                  <tr>
                    <td>Item name</td>
                    <td class="text-right-aligned">Sum</td>
                    <td class="text-right-aligned">Count</td>
                  </tr>
              </thead>
              <tbody>
              <% Item.for_backlog_statistics(backlog).each do |item| %>
                  <tr>
                    <td>
                      <%= item.name %>
                      <%= link_to 'Show details', backlog_item_estimations_path(backlog,item), class: 'show-detail-estimations' %>
                      <div style="display:none;"></div>
                    </td>
                    <td class="text-right-aligned">
                      <%= item.s %>
                    </td>
                    <td class="text-right-aligned">
                      <%= item.c %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= render inline: '</div>' if i%2 == 1 %>
      <% i += 1 %>
  <% end %>
</div>

app/views/estimations/_form.html.erb
<% add_pos_field ||= false %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @item.name %>
  </div>
  <div class="panel-body">
    <%= @item.description %>
  </div>
  <div class="panel-body">
    <%= render 'values' %>
  </div>
  <div class="panel-footer">
    <%= form_tag estimations_pass_backlog_path(@item.backlog), method: :post do %>
        <div class="well">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-1"></div>
            <% points = Point.all.collect(&:value) %>
            <% points.each do |point| %>
                <% percent = top_percent_for_value(points, point) %>
                <div class="col-md-1">
                    <%=radio_button_tag 'value', point, false, disabled: false, id: "value_#{point}", class: 'point-radio'%>
                    <%=label_tag "value_#{point}", class: 'point-label' do%>
                        <div class="point-indicator" style="top:<%=percent%>">
                            <%=point%>
                        </div>
                    <% end %>
                </div>
            <% end %>
            <div class="col-md-1"></div>
          </div>
          <div class="row point-legend">
            <div class="col-md-6">
                <span class="glyphicon glyphicon-arrow-left"></span> simple, low complexity
            </div>
            <div class="col-md-6">
              high complexity, unclear <span class="glyphicon glyphicon-arrow-right"></span>
            </div>
          </div>
        </div>
        </div>
        <%= hidden_field_tag 'item_id', @item.id %>
        <% if add_pos_field == true %>
            <%= hidden_field_tag 'pos', params[:pos] || 1 %>
        <% end %>
        <br>
        <%= link_to 'Cancel', user_path(current_user), class: 'btn btn-default' %>
        <%= submit_tag 'Estimate', class: 'btn btn-primary right-aligned' %>
    <% end %>
  </div>
</div>

app/views/estimations/_overview.html.erb
<% i = 0 %>
<div class="container-fluid">
  <% Backlog.all.each do |backlog| %>
      <%= render inline: '<div class="row">' if i%2 == 0 %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%=backlog.name%>
          </div>
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt>Total items:</dt>
              <dd><span class="label label-default"><%=backlog.items.count%></span></dd>
              <dt>Items to be estimated:</dt>
              <dd><span class="label label-primary"><%=Item.for_backlog_and_estimator_not_estimated_yet(backlog,user).size%></span></dd>
              <dt>Items already estimated:</dt>
              <dd><span class="label label-success"><%=Item.for_backlog_and_estimator_already_estimated(backlog,user).size%></span></dd>
            </dl>
          </div>

          <% if current_user?(user) %>
              <% size_items_to_be_estimated_initially = 0;
                 size_items_to_be_estimated_next = 0;
                 size_items_to_be_possibly_reestimated = 0;%>
              <div class="panel-footer">
                <% if backlog.items.any_to_be_estimated_initially?(backlog, user) {|size| size_items_to_be_estimated_initially = size}%>
                    <%= link_to "Estimate initially (#{size_items_to_be_estimated_initially})", estimations_initial_backlog_path(backlog), class: 'btn btn-danger' %>
                <% end %>
                <% if backlog.items.any_to_be_estimated_next?(backlog, user) {|size| size_items_to_be_estimated_next = size}%>
                    <%= link_to "Estimate as next (#{size_items_to_be_estimated_next})", estimations_next_backlog_path(backlog), class: 'btn btn-primary' %>
                <% end %>
                <% if backlog.items.any_to_be_possibly_reestimated?(backlog) {|size| size_items_to_be_possibly_reestimated = size}%>
                    <%= link_to "Re-estimate (#{size_items_to_be_possibly_reestimated})", estimations_reestimate_backlog_path(backlog), class: 'btn btn-default' %>
                <% end %>
              </div>
          <% end %>
        </div>

      </div>
      <%= render inline: '</div>' if i%2 == 1 %>
      <% i += 1 %>
  <% end %>
</div>

app/views/estimations/_progress.html.erb
<% percentage = percentage(@estimated,@total) %>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%=@estimated%>" aria-valuemin="0" aria-valuemax="<%=@total%>" style="min-width: 2em;width:<%=percentage%>">
    <%=percentage%>
  </div>
</div>

app/views/estimations/_value_per_user.html.erb
<% @estimations.each do |estimation| %>
    <b><%=estimation.value%></b> by <%=link_to estimation.name, user_path(estimation.user_id)%>
    <br>
<% end %>

app/views/estimations/_values.html.erb
<% if @item.estimations.count > 0 %>
    <div>
    <h5>Estimations so far:</h5>
        <% @item.estimations.each do |e| %>
            <% css_class = e.initial? ? 'label label-primary' : 'label label-default' %>
            <span class="<%=css_class%>"><%=e.value%></span> by <%=e.estimator.name %>
          <br>
        <% end %>
    </div>
<% end %>

app/views/estimations/index.html.erb
<% if current_user.member? %>
    <%= render 'estimations/overview', user: current_user %>
<% end %>

<% if current_user.admin? %>
    <%= render 'estimations/dashboard' %>
<% end %>

app/views/estimations/initial.html.erb
<%= render 'progress' %>
<%= render 'form' %>

app/views/estimations/next.html.erb
<%= render 'progress' %>
<%= render 'form' %>

app/views/estimations/reestimate.html.erb
<%= render 'progress' %>
<%= render 'form', add_pos_field: true %>