config/routes.rb
MagicEstimation::Application.routes.draw do

  

  root to: 'backlogs#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :backlogs do
    resources :items, only: [:create, :edit, :update, :destroy] do
      member do
        post :assign, to: :assign
      end
      resources :estimations, only: [:index]
    end
    member do
      get '/estimations/initial', to: 'estimations#initial'
      get '/estimations/next', to: 'estimations#next'
      get '/estimations/reestimate', to: 'estimations#reestimate'
      post '/estimations/pass', to: 'estimations#pass'
    end
  end
  resources :estimations, only: [:index]
end

app/models/backlog.rb
class Backlog < ActiveRecord::Base

  validates :name, :description, :creator, presence: true
  has_many :items, dependent: :destroy
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :estimations, through: :items
  has_many :estimators, through: :estimations, source: :estimator

end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController

  before_action :require_user, except: [:index]
  before_action :set_backlog, only: [:show, :edit, :update]

  def index
    @backlogs = Backlog.all
    respond_to do |format|
      format.html
    end
  end

  def new
    @backlog = Backlog.new
  end

  def create
    @backlog = Backlog.new(backlog_params)
    @backlog.creator = current_user
    if @backlog.save
      flash[:notice] = "Backlog #{@backlog.name} saved."
      redirect_to backlogs_path
    else
      render :new
    end
  end

  def show
    if params[:item]
      @item = Item.find(params[:item])
    else
      @item = Item.new
      @item.backlog = @backlog
    end
  end

  def edit
  end

  def update
    if @backlog.update(backlog_params)
      flash[:notice] = 'Backlog has been updated successfully.'
      redirect_to backlog_path(@backlog)
    else
      render :edit
    end
  end

  def destroy
    if Backlog.destroy(params[:id])
      flash[:notice] = 'Backlog has been destroyed.'
      redirect_to backlogs_path
    end
  end

  private

  def set_backlog
    @backlog = Backlog.find(params[:id])
  end

  def backlog_params
    params.require(:backlog).permit(:name, :description)
  end

end

app/views/backlogs/_backlog.html.erb
<% buttons ||= {} %>
<div class="panel panel-default">
  <div class="panel-heading"><%= backlog.name %></div>
  <div class="panel-body">
    <%= backlog.description %>
  </div>
  <% if logged_in? %>
      <div class="panel-footer">
        <%= link_to 'Show', backlog_path(backlog), class: 'btn btn-default' if buttons[:show] %>
        <% if current_user.admin? %>
            <%= link_to 'Edit', edit_backlog_path(backlog), class: 'btn btn-primary' if buttons[:edit] %>
            <%= link_to 'Destroy', backlog_path(backlog), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' if buttons[:destroy] %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/backlogs/_form.html.erb
<%= render 'shared/errors', obj: @backlog %>
<div class="well">
  <%= form_for @backlog do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'name of the backlog' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: 'form-control description', placeholder: 'short description of this backlog' %>
      </div>
      <%= f.submit 'Save', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/backlogs/edit.html.erb
<%= render 'form' %>

app/views/backlogs/index.html.erb
<%= render 'shared/title', title: 'All backlogs'%>
<% @backlogs.each do |backlog| %>
    <%= render 'backlog', backlog: backlog, buttons: { show: true } %>
<% end %>

app/views/backlogs/new.html.erb
<%= render 'shared/title', title: 'New backlog' %>
<%= render 'form' %>

app/views/backlogs/show.html.erb
<%= render 'shared/title', title: "Showing <b>#{@backlog.name}</b> including <b>#{@backlog.items.count}</b> items".html_safe %>
<%= render 'backlogs/backlog', backlog: @backlog, buttons: {edit: true, destroy: true} %>
<% if current_user.admin? %>
    <%= render 'items/form' %>
<% end %>

<div class="container-fluid">
    <%= render 'shared/subtitle', title: 'Existing items' %>
    <% i = 0 %>
    <% @backlog.items.each do |item| %>
        <%= render inline: '<div class="row">'.html_safe if i%2 == 0 %>
        <%= render 'items/item', item: item %>
        <%= render inline: '</div>'.html_safe if i%2 == 1 %>
        <% i += 1%>
    <% end %>
</div>
<% if current_user.admin? %>
    <%= render 'items/assign_item_to_user' %>
<% end %>