config/routes.rb
MagicEstimation::Application.routes.draw do

  

  root to: 'backlogs#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]
  resources :backlogs do
    resources :items, only: [:create, :edit, :update, :destroy] do
      member do
        post :assign, to: :assign
      end
      resources :estimations, only: [:index]
    end
    member do
      get '/estimations/initial', to: 'estimations#initial'
      get '/estimations/next', to: 'estimations#next'
      get '/estimations/reestimate', to: 'estimations#reestimate'
      post '/estimations/pass', to: 'estimations#pass'
    end
  end
  resources :estimations, only: [:index]
end

app/views/layouts/_messages.html.erb
<% flash.each do |key,msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%=key==:notice ? 'success' : 'danger'%> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%=msg%>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand brand' do%>
        Magic<span class="glyphicon glyphicon-grain"></span>Estimation
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if !logged_in? %>
            <form class="navbar-form navbar-left">
              <%= link_to 'Register', register_path, class: 'btn btn-primary btn-small', 'role' => 'button' %>
              <%= link_to 'Login', login_path, class: 'btn btn-success btn-small', 'role' => 'button' %>
            </form>
        <% else %>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'false' do %>
                  Backlogs <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu" role="menu">
                <% recent_backlogs.each do |backlog| %>
                    <li>
                      <%= link_to backlog_path(backlog) do %>
                          <span class="glyphicon glyphicon-leaf"></span>
                          <%= backlog.name %>
                      <% end %>
                    </li>
                <% end %>
                <% if current_user.admin? %>
                    <li class="divider"></li>
                    <li>
                      <%= link_to new_backlog_path do %>
                          <span class="glyphicon glyphicon-plus"></span>
                          Backlog
                      <% end %>
                    </li>
                <% end %>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left">
            <%= link_to estimations_path, class: 'btn btn-primary' do%>
                <% if current_user.admin? %>
                    Dashboard
                <% else %>
                    Estimation room
                <% end %>
            <% end %>
          </form>
          <form class="navbar-form navbar-right">
            <%= link_to "#{current_user.name}'s profile", user_path(current_user), class: 'btn btn-primary' %>
            <%= link_to 'Logout', logout_path, class: 'btn btn-danger btn-small' %>
          </form>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MagicEstimation</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>

<div id="main" role="main">
  <div class="container">

        <%= render 'layouts/messages' %>
        <%= yield %>
  </div>
  <footer>
  </footer>
</div>
</body>
</html>